#!/usr/bin/env node
/**
 * Regenerates src/types/schema.ts from assets/openapi.json via openapi-typescript.
 *
 * This file used to be regenerated by a one-off `npx openapi-typescript` invocation
 * with no recorded version or flags, which let it drift months behind the committed
 * spec. Run `npm run generate-openapi-types` after updating assets/openapi.json.
 *
 * Two deviations from stock openapi-typescript output:
 * - Every operation's x-auth-scheme header parameter is dropped before generation.
 *   It carries an inline enum, so `enum: true` would otherwise mint one junk
 *   `PathsApi...XAuthScheme` enum per endpoint (~1,700 of them). No code types
 *   against request headers.
 * - `export type schema = components["schemas"]` is appended; hand-written code
 *   imports that alias throughout.
 * - Enum values of "" (e.g. DeviceFacetEnum) come out of openapi-typescript as a
 *   member with an empty NAME, which is invalid TypeScript; they are renamed to
 *   `EMPTY` (the wire value stays "").
 * - All `discriminator` blocks are stripped before generation. openapi-typescript
 *   injects a required single-value enum property per discriminated variant
 *   (e.g. `strategy: WeeklyRepeatingScheduleTypeStrategy`), and under `enum: true`
 *   that nominal enum intersects the base type's real enum (`ScheduleStrategyEnum`)
 *   to `never`, collapsing the whole object type. Hand-written code narrows these
 *   unions structurally and never used the injected properties.
 *
 * Note: src/types/zod-schemas.ts is generated separately (npm run generate-schemas).
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const specPath = path.join(__dirname, "..", "assets", "openapi.json");
const outPath = path.join(__dirname, "..", "src", "types", "schema.ts");

const spec = JSON.parse(fs.readFileSync(specPath, "utf8"));

let strippedAuthHeaders = 0;
for (const pathItem of Object.values(spec.paths ?? {}) as any[]) {
  for (const op of Object.values(pathItem) as any[]) {
    if (!op || !Array.isArray(op.parameters)) continue;
    const before = op.parameters.length;
    op.parameters = op.parameters.filter(
      (p: any) => !(p?.in === "header" && p?.name?.toLowerCase() === "x-auth-scheme")
    );
    strippedAuthHeaders += before - op.parameters.length;
  }
}
console.log(`Stripped ${strippedAuthHeaders} X-Auth-Scheme header parameters`);

let strippedDiscriminators = 0;
function stripDiscriminators(node: any) {
  if (Array.isArray(node)) {
    node.forEach(stripDiscriminators);
  } else if (node && typeof node === "object") {
    if (node.discriminator && typeof node.discriminator === "object") {
      delete node.discriminator;
      strippedDiscriminators++;
    }
    Object.values(node).forEach(stripDiscriminators);
  }
}
stripDiscriminators(spec);
console.log(`Stripped ${strippedDiscriminators} discriminator blocks`);

const ast = await openapiTS(spec, {
  rootTypes: true,
  rootTypesNoSchemaPrefix: true,
  enum: true,
});

let emptyEnumMembers = 0;
const body = astToString(ast).replace(/^(\s*)= ("",?)$/gm, (_, indent, value) => {
  emptyEnumMembers++;
  return `${indent}EMPTY = ${value}`;
});
console.log(`Renamed ${emptyEnumMembers} empty-string enum members to EMPTY`);

const output = body + '\nexport type schema = components["schemas"];\n';
fs.writeFileSync(outPath, output);
console.log(`Wrote ${outPath} (${output.split("\n").length} lines)`);
