import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import {
  dismissPolicyAlert,
  getExpiringPolicyAlerts,
  getPolicyAlertDetails,
  getPolicyAlertGroups,
  getPolicyAlerts,
  getUnhealthyDeviceAlerts,
} from "../api/policy-alerts-tool-api.js";
import {
  ApiPayloadSchema,
  OUTPUT_SCHEMA,
  TOOL_ARGS,
  type ToolArgs,
} from "../types/policy-alerts-tool-types.js";
import { extractFromToolExtra } from "../util.js";

const TOOL_NAME = "policy-alerts-tool";
const TOOL_DESCRIPTION = `
Retrieves Rhombus policy alerts — alerts generated by user-defined alert policies when configured events occur: AI/computer-vision events (motion, people, vehicles, faces, license plates, unusual behavior), device status changes (disconnection, low battery), physical/visual tamper, and access-control events. Alerts are NOT the same as notifications (only some alerts notify, per user settings). Can also report which alert labels have been seen. Supports filtering by existing/expiring, time range, device UUIDs or location UUIDs — pagination and per-queryType requirements are documented on the parameters.

IMPORTANT: queryType "unhealthy-devices" returns HISTORICAL device-health alert notifications, not live status — it can be empty while devices are offline. To check which devices are currently online/offline, use get-entity-tool instead (filterBy on its "connected" field).
`;

const TOOL_HANDLER = async (args: ToolArgs, extra: unknown) => {
  const payload = ApiPayloadSchema.parse(args);

  const { requestModifiers, sessionId } = extractFromToolExtra(extra);

  let ret;
  switch (args.queryType) {
    case "existing":
      ret = await getPolicyAlerts(
        payload,
        requestModifiers,
        sessionId
      );
      break;
    case "expiringSoon":
      ret = await getExpiringPolicyAlerts(
        payload,
        requestModifiers,
        sessionId
      );
      break;
    case "details":
      if (!args.alertUuid) {
        throw new Error("alertUuid is required for 'details' queryType");
      }
      ret = await getPolicyAlertDetails(
        args.alertUuid,
        requestModifiers,
        sessionId
      );
      break;
    case "dismiss":
      if (!args.alertUuid) {
        throw new Error("alertUuid is required for 'dismiss' queryType");
      }
      ret = await dismissPolicyAlert(
        args.alertUuid,
        requestModifiers,
        sessionId
      );
      break;
    case "unhealthy-devices":
      ret = await getUnhealthyDeviceAlerts(
        requestModifiers,
        sessionId
      );
      break;
    case "alert-groups":
      ret = await getPolicyAlertGroups(
        payload,
        requestModifiers,
        sessionId
      );
      break;
    default:
      throw new Error(`Unsupported queryType: ${args.queryType}`);
  }

  return {
    content: [{ type: "text" as const, text: JSON.stringify(ret) }],
    structuredContent: ret,
  };
};

export function createTool(server: McpServer) {
  server.registerTool(
    TOOL_NAME,
    {
      title: "Policy Alerts",
      description: TOOL_DESCRIPTION,
      inputSchema: TOOL_ARGS,
      outputSchema: OUTPUT_SCHEMA.shape,
      // `dismiss` cannot be undone, which is what destructiveHint is for.
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    TOOL_HANDLER
  );
}
